export const GET_TOURNAMENT = 'GET_TOURNAMENT';
export const TOURNAMENT_ERROR = 'TOURNAMENT_ERROR';
export const GET_TOURNAMENT_RESULTS = 'GET_TOURNAMENT_RESULTS';
export const TOURNAMENT_RESULTS_ERROR = 'TOURNAMENT_RESULTS_ERROR';
export const GET_TOURNAMENT_CONTESTANTS = 'GET_TOURNAMENT_CONTESTANTS';
export const TOURNAMENT_CONTESTANTS_ERROR = 'TOURNAMENT_CONTESTANTS_ERROR';
